image: node:14

stages:
  - build
  - test
  - analyze

cache:
  paths:
    - node_modules/
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


backend_build:
  image: maven:3.8.4-openjdk-17
  stage: build
  script:
    - cd backend
    - chmod +x mvnw
    - ./mvnw clean install -DskipTests
  artifacts:
    paths:
      - backend/target/

frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build --no-progress 2>&1 >/dev/null || true
  artifacts:
    paths:
      - frontend/build/

frontend_test:
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm test

backend_test:
  image: maven:3.8.4-openjdk-17
  stage: test
  script:
    - cd backend
    - chmod +x mvnw
    - ./mvnw test

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: analyze
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - main
    - develop
